name: Release
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 22.23.1
      - name: install dependencies
        run: yarn install
      - name: publish
        env:
          ACCESS_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run publish

  publish_on_mac_arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 22.23.1
      - name: install dependencies
        run: yarn install
      - name: publish
        env:
          ACCESS_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run publish --arch="arm64"

  publish_on_mac_x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 22.23.1
      - name: install dependencies
        run: yarn install
      - name: publish
        env:
          ACCESS_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run publish --arch="x64"

  publish_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 22.23.1
      - name: install dependencies
        run: yarn install
      - name: publish
        env:
          ACCESS_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run publish
